03-dataframe方法2

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
url = "https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv"
df=pd.read_csv(url)
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [3]:
#取列
df['Age']

0      22.0
1      38.0
2      26.0
3      35.0
4      35.0
       ...
886    27.0
887    19.0
888     NaN
889    26.0
890    32.0
Name: Age, Length: 891, dtype: float64

In [4]:
df[['Name','Sex','Pclass']]

                                                  Name     Sex  Pclass
0                              Braund, Mr. Owen Harris    male       3
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female       1
2                               Heikkinen, Miss. Laina  female       3
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female       1
4                             Allen, Mr. William Henry    male       3
..                                                 ...     ...     ...
886                              Montvila, Rev. Juozas    male       2
887                       Graham, Miss. Margaret Edith  female       1
888           Johnston, Miss. Catherine Helen "Carrie"  female       3
889                              Behr, Mr. Karl Howell    male       1
890                                Dooley, Mr. Patrick    male       3

[891 rows x 3 columns]

In [6]:
df.loc[0]

PassengerId                          1
Survived                             0
Pclass                               3
Name           Braund, Mr. Owen Harris
Sex                               male
Age                               22.0
SibSp                                1
Parch                                0
Ticket                       A/5 21171
Fare                              7.25
Cabin                              NaN
Embarked                             S
Name: 0, dtype: object

In [7]:
df.loc[0:4,['Name','Sex','Pclass']]#含最后一行

                                                Name     Sex  Pclass
0                            Braund, Mr. Owen Harris    male       3
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female       1
2                             Heikkinen, Miss. Laina  female       3
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female       1
4                           Allen, Mr. William Henry    male       3

In [8]:
df.loc[:,'Name'].head()#注意是index和columns

0                              Braund, Mr. Owen Harris
1    Cumings, Mrs. John Bradley (Florence Briggs Th...
2                               Heikkinen, Miss. Laina
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)
4                             Allen, Mr. William Henry
Name: Name, dtype: object

In [9]:
df.loc[[0,65,79],['Name','Survived']]

                        Name  Survived
0    Braund, Mr. Owen Harris         0
65  Moubarek, Master. Gerios         1
79  Dowdell, Miss. Elizabeth         1

In [10]:
#注意到索引单独一行一列返回序列多个返回DF

In [11]:
df.iloc[:5,:5]#纯数字

,PassengerId,Survived,Pclass,Name,Sex
0,1,0,3,"Braund, Mr. Owen Harris",male
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female
2,3,1,3,"Heikkinen, Miss. Laina",female
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female
4,5,0,3,"Allen, Mr. William Henry",male

In [12]:
df.iloc[0:1,:]#返回DF

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.25,NaN,S

In [13]:
#筛选

In [15]:
df[df['Survived']==1].head(1)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C

In [17]:
df[(df['Sex'] == 'female') & (df['Survived'] == 1)].head(2)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S

In [18]:
df[df['Pclass'].isin([1, 2])].head(2)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S

In [20]:
df[df['Name'].str.contains('Mr')].head(2)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C

In [21]:
df[df['Age'].notna()].head(2)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C

In [22]:
df.query("Sex == 'male' and Survived == 1").head(3)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
17,18,1,2,"Williams, Mr. Charles Eugene",male,NaN,0,0,244373,13.0,NaN,S
21,22,1,2,"Beesley, Mr. Lawrence",male,34.0,0,0,248698,13.0,D56,S
23,24,1,1,"Sloper, Mr. William Thompson",male,28.0,0,0,113788,35.5,A6,S

In [23]:
#修改数据

In [28]:
#直接修改
print(df.loc[0,['Name']])
df.loc[0,['Name']]='name1'
print(df.loc[0,['Name']])

Name    Braund, Mr. Owen Harris
Name: 0, dtype: object
Name    name1
Name: 0, dtype: object

In [30]:
#新增列
df['new']=df['Age']-df['Age'].mean()
print(df['new'].head())

0   -7.699118
1    8.300882
2   -3.699118
3    5.300882
4    5.300882
Name: new, dtype: float64

In [32]:
#df['IsAlone'] = (df['FamilySize'] == 1).astype(int)

In [38]:
#处理缺失值
#df[df['Age']=='NaN'].head(2)报错，
np.nan==np.nan

False

In [41]:
#正确写法
df[df['Age'].isna()].head(2).fillna(df['Age'].median())

D:\Temp\ipykernel_70560\1323111340.py:2: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[df['Age'].isna()].head(2).fillna(df['Age'].median())

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,new
5,6,0,3,"Moran, Mr. James",male,28.0,0,0,330877,8.4583,28.0,Q,28.0
17,18,1,2,"Williams, Mr. Charles Eugene",male,28.0,0,0,244373,13.0000,28.0,S,28.0

In [42]:
df[df['Age'].isna()].head(2)#说明不改变源列表

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,new
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q,NaN
17,18,1,2,"Williams, Mr. Charles Eugene",male,NaN,0,0,244373,13.0000,NaN,S,NaN

In [43]:
df[df['Age'].isna()].head(2).dropna(subset=['Age', 'Embarked'])#一个不剩

Empty DataFrame
Columns: [PassengerId, Survived, Pclass, Name, Sex, Age, SibSp, Parch, Ticket, Fare, Cabin, Embarked, new]
Index: []

In [44]:
df[df['Age'].isna()].head(2)#依旧不变

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,new
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q,NaN
17,18,1,2,"Williams, Mr. Charles Eugene",male,NaN,0,0,244373,13.0000,NaN,S,NaN

In [46]:
df.dropna(axis=1, thresh=len(df)*0.5)#删除缺失超过50%的列
df.dropna(thresh=len(df.columns)*0.5)
print(len(df))

891

In [ ]:
df['Pclass'] = df['Pclass'].astype(str)

In [48]:
df['Sex_num'] = df['Sex'].map({'male':0, 'female':1})
df['Sex_num'].head()

0    0
1    1
2    1
3    1
4    0
Name: Sex_num, dtype: int64