In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
#引入数据
movies=pd.read_csv("movies.csv")
ratings=pd.read_csv("ratings.csv")
tags=pd.read_csv("tags.csv")
links=pd.read_csv("links.csv")

In [3]:
#检查一下
movies.head(2)

   movieId             title                                       genres
0        1  Toy Story (1995)  Adventure|Animation|Children|Comedy|Fantasy
1        2    Jumanji (1995)                   Adventure|Children|Fantasy

In [5]:
#df = 左表.merge(右表, on=连接键, how=连接方式, suffixes=重名处理)
df1=ratings.merge(movies,on='movieId')#两边都有的才会被连接
df1.head(2)

,userId,movieId,rating,timestamp,title,genres
0,1,1,4.0,964982703,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
1,1,3,4.0,964981247,Grumpier Old Men (1995),Comedy|Romance

In [13]:
#检查数据
print(len(ratings))
print(len(df1))#how=inner应该是连接后略少，left不变
#有没有意外的NAN
print(df1.isnull().sum())
#列名有没有冲突，如果有col_x,col_y说明没处理
print(df.columns.tolist())

100836
100836
userId       0
movieId      0
rating       0
timestamp    0
title        0
genres       0
dtype: int64
['userId', 'movieId', 'title', 'genres', 'rating', 'timestamp', 'tag']

In [8]:
df=df1.merge(tags[['userId','movieId','tag']],on=['userId','movieId'],how='left')
df.head(2)

,userId,movieId,rating,timestamp,title,genres,tag
0,1,1,4.0,964982703,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,NaN
1,1,3,4.0,964981247,Grumpier Old Men (1995),Comedy|Romance,NaN

In [9]:
#重回排序
df = df[['userId', 'movieId', 'title', 'genres', 'rating', 'timestamp', 'tag']]
df.head(2)

,userId,movieId,title,genres,rating,timestamp,tag
0,1,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,4.0,964982703,NaN
1,1,3,Grumpier Old Men (1995),Comedy|Romance,4.0,964981247,NaN

In [14]:
#同理检查数据
print(len(df1))
print(len(df))
print(df.isnull().sum())
print(df.columns.tolist())

100836
102677
userId           0
movieId          0
title            0
genres           0
rating           0
timestamp        0
tag          99201
dtype: int64
['userId', 'movieId', 'title', 'genres', 'rating', 'timestamp', 'tag']

In [15]:
#补充还可以all_emp_df = pd.concat([emp_df, emp2_df])
#这里指的是完全相同的列表拼接

In [16]:
#重新设置列表index
"""
all_emp_df.reset_index(inplace=True)
"""

'\nall_emp_df.reset_index(inplace=True)\n'

In [17]:
#数据清洗
"""
之前的isnull(),fillna()dropna()
"""

'\n之前的isnull(),fillna()dropna()\n'

In [22]:
#重复值
df.nunique()

userId         610
movieId       9724
title         9719
genres         951
rating          10
timestamp    85043
tag           1543
dtype: int64

In [24]:
print(df.duplicated('movieId'))
#df.drop_duplicates([, ], inplace=True)

0         False
1         False
2         False
3         False
4         False
          ...
102672     True
102673     True
102674     True
102675     True
102676     True
Length: 102677, dtype: bool

In [ ]:
#emp_df.drop(emp_df[(emp_df.sal > 8000) | (emp_df.sal < 2000)].index)
#avg_sal = np.mean(emp_df.sal).astype(int)
#emp_df.replace({'sal': [1800, 9000], 'comm': 800}, {'sal': avg_sal, 'comm': 1000})